[workspace]
authors = ["Kupryashin_ev <kupryashin.ev@yandex.ru>"]
channels = ["conda-forge"]
name = "point-vlm"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --user --name pointvlm --display-name pointvlm"
jup = "pixi run jupyter notebook --port 8898 --ip 0.0.0.0"

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.10.*"
peft = ">=0.15.2,<0.16"
bitsandbytes = ">=0.46.0,<0.47"
transformers = "==4.47.0"
ipykernel = ">=6.29.5,<7"
pillow = ">=11.2.1,<12"
pytorch-gpu = "*"
matplotlib = ">=3.10.3,<4"
tensorboardx = ">=2.6.2.2,<3"
scikit-learn = ">=1.7.0,<2"

[feature.notebooks.dependencies]
jupyter = "*"
ipykernel = ">=6.29.5,<7"

[feature.code-quality.dependencies]
ruff = "*"

[environments]
dev = ["notebooks", "code-quality"]
